### PR TITLE
Python and C programs

### PR DESCRIPTION
**Pull request by FAHADPN**
Simple Calculator for addition, subtraction, multiplication and division . And C programs for finding armstrong and prime number, factorial in recursive and non-recursive method and  to check palindrome,

### CODE REVIEW

**Comment by Bhavye-Malhotra** [comment]
Hey, I would like you to add the comments for your approach to these programs. Please explain it by commenting on the code.

**Comment by FAHADPN** [comment]
> Hey, I would like you to add the comments for your approach to these programs. Please explain it by commenting on the code.

yeah sure,  I will add comments ASAP

**Comment by BAKCHODGUNDA** [comment]
Can i add my projects in this?

**Comment by FAHADPN** [comment]
> Not accepting anymore due to TOS of digitalocean

Why was this PR labelled as invalid? Can you please explain so that I can make necessary changes accordingly.

**Comment by achitJ** [comment]
> > Not accepting anymore due to TOS of digitalocean
> 
> Why was this PR labelled as invalid? Can you please explain so that I can make necessary changes accordingly.

Issues for the said programmes have already been raised, so this will create duplicates.

**Pull request closed without merging**
